# Generated by Django 6.0.7 on 2026-07-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Faça o upload do seu currículo em PDF",
                null=True,
                upload_to="cv/",
            ),
        ),
    ]
