"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-qy&v1=4p252(25!66s(!ika-qh&0*vxdpvxg2gg&ix1*#77)xk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Meus apps
    'portfolio',
    'tinymce',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========================================
# 1. CONFIGURAÇÃO DO EDITOR RICO (TINYMCE)
# Forçando o Modo Escuro e a largura 100%
# ==========================================
TINYMCE_DEFAULT_CONFIG = {
    "height": "400px",
    "width": "100%",  # Corrige o bug da caixa espremida
    "menubar": False,
    "skin": "oxide-dark",  # Tema escuro do editor
    "content_css": "dark", # Fundo escuro para a área de digitação
    "toolbar": "undo redo | formatselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link | removeformat",
    "plugins": "advlist autolink lists link image charmap preview anchor searchreplace visualblocks code fullscreen insertdatetime media table code help wordcount",
}

# ==========================================
# 2. CONFIGURAÇÕES DO PAINEL SAAS (JAZZMIN)
# ==========================================
JAZZMIN_SETTINGS = {
    "site_title": "SaaS Admin",
    "site_header": "Gerência do Portfólio",
    "site_brand": "Painel de Controle",
    "welcome_sign": "Bem-vindo à plataforma de gerência",
    "copyright": "Caio Murilo",
    
    # Adiciona links no menu superior
    "topmenu_links": [
        {"name": "Início",  "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # Substitui os links em inglês no perfil do usuário (Canto superior direito)
    "usermenu_links": [
        {"name": "Visualizar Site ao Vivo", "url": "/", "new_window": True, "icon": "fas fa-eye"},
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "portfolio.Profile": "fas fa-id-card",
        "portfolio.Project": "fas fa-briefcase",
        "portfolio.HomeSection": "fas fa-layer-group",
        "portfolio.Page": "fas fa-file-alt",
    },
    
    "order_with_respect_to": ["portfolio", "auth"],
    
    # Desligamos a engrenagem (UI Builder) pois o layout já está definido
    "show_ui_builder": False, 
}

# ==========================================
# 3. AJUSTE FINO DO VISUAL E BOTÕES
# ==========================================
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "theme": "darkly", # Mantém o dark mode base
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme_color": "default",
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}